name = "subway-fit-api"
main = "src/index.ts"
compatibility_date = "2026-08-16"

[[d1_databases]]
binding = "DB"
database_name = "subway-fit-db"
database_id = "f1bf8067-002b-4773-9161-034fe3e1ce3c"

[vars]
ALLOWED_ORIGIN = "http://localhost:5173"
FIREBASE_PROJECT_ID = "cardio-surfer"
